baseURL = "https://darrenxyli.github.io"
languageCode = "en-us"
hasCJKLanguage = true
title = "Xinyang Li"
theme = "hugo_theme_pickles"

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 5
